export const SET_CURRENT_MENU = 'SET_CURRENT_MENU';
export const SET_BREAD_CRUMB_TITLE = 'SET_BREAD_CRUMB_TITLE';
export const SET_BREAD_CRUMB = 'SET_BREAD_CRUMB';

export const ROUTE_PUSH = 'ROUTE_PUSH';

export const GET_MONITOR_CONFIG = 'GET_MONITOR_CONFIG';
